language: node_js
node_js:
  - '4.2'
script:
  - npm run lint
  - npm run test
after_success:
  - ./bin/build-gh-pages-travis
deploy:
  provider: releases
  skip_cleanup: true
  on:
    repo: singpath/singpath
    tags: true
  file: dist/singpath.zip
  api_key:
    secure: CDaFMzgCm2GVlrc8nKH02qB9fk52PvKxOa9LfH7eagGCgvRzBLIrgzYfXXgAzpdSzSUCw503ndmw0wxDIPopbpFyMKzh4Zi+qZoaEfn+MIjUBAIEB43sGdY4ox8Hqki/TdhgAlaWt921Kxms2RDuNkD/l2GO7y1gq0nKGZ56FjdvufFdoPtLBy5Aa97hGq2OezRxXYMWzh2Ml0eAVwd6Fu5MTuOKDqRy7+tg2HYcTtrhEREIgHdSFbuSy/xi26JugBgGyFJOWYyHl/bSE11lxOZlw6FQroO4TuGQKup9BZjl+gl0811+Ffwg4Vo0/DrUDF4UIM8xzX28ZnFuy/TkQw5u79B78fXCxAWTHhi1FBRriHdEG9OwP6BDOycvFNV/Sb/xy9I971IF+RgirdqeaFOMEPz/CYZEoAaUlvwQXpyhVmoMKRolrrLX3G6zZADhDFxInHQB44kY2LsWNos84WXYm/+bjNkWqn4jXySF0m7pSQDb3H4U0W4aSM7IFvW53LxYuOnAgzjsxSuPCXd6yKiMwbtQb2P2dksVH4vwheT60kphJlnsWiUIE/ErLFJrmb0IhYvhe2wcjt6KAwwCnRCA8mMxsKF8Vsw4bVG8K+MiZ9wkplRkyGofbBXgrw68/UcXWzz7kmFABmlxIhvIYLIczLIoHl83TbYp5efwR3c=
